global using Microsoft.EntityFrameworkCore;
global using Pronia.Areas.Manage.ViewModels.Setting;
global using Pronia.Areas.Manage.ViewModels.Product;
global using Pronia.ViewModels.Account;
global using Microsoft.AspNetCore.Mvc;
global using Pronia.ViewModels;
global using Pronia.Helpers;
global using Pronia.Models;
global using Pronia.DAL;